pop_culture <- sidebarLayout(
  sidebarPanel(
    wellPanel(
      br(),
      br(),
      br(),
      br(),
      br(),
      br(),
      br(),
      br(),
      br(),
      br(),
      br(),
      textInput("user1", h4("Lets compare public figures. Please enter the first user."), "realDonaldTrump"),
      textInput("user2", h4("Please enter the second user."), "BarackObama"),
      br(),
      br(),
      br(),
      selectInput("checks", h5("What should we compare?"), choices = c( "# of Tweets" = "statusesCount",
                                                                       "Followers" = "followersCount"), 
                  selected = "statusesCount"),
      submitButton("Search")
    ),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    wellPanel(
      textInput("public_figure", h4("Which public figure would you like to look up?"), "Kim Kardashian"),
      selectInput("num_of_tweets", h5("How many tweets would you like to look at?"), c(100, 500, 1000)),
      submitButton("Search")
    ),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br()
  ),
  mainPanel(
    img(src = 'icon.jpg', align = "right", height = 80, width = 100),
    titlePanel("The Interaction Between Public Figures and Twitter"),
    p("Twitter is the perfect platform for users to connect with their favorite public figures, and for 
       public figures to share with their fans. Below, we are able to explore the relationship between two different
       public figures and examine their following. In addition, we can examine the most commonly associated words in tweets
       with a particular public figures. From this, we are able to make generalizations about their perception and popularity."),
    titlePanel("Compare Two Different Twitter Users"),
    h4(textOutput("data_table_description")),
    fluidRow(
      column(1, 
        br(),
        br(),
        br(),
        htmlOutput("user1_image", align = "left"),
        br(),
        htmlOutput("user2_image", align = "left")
      ),
      column(8,
        tableOutput("compare_users_table")
      )
    ),
    plotOutput("compare_users_graph", width = "100%", height = "100%"),
    titlePanel("Word Cloud Builder"),
    h4(textOutput("word_cloud_text")),
    plotOutput("public_figure_word_cloud", width = "300%", height = "300%", inline =  TRUE)
  )
)
